In [20]:
# what is numpy 
# it is a  python_library
# it is used for all numerical operation in data analyst/ data_science
# its deals with numercal feature
# playing with arrays

In [21]:
import numpy as np

In [22]:
a=np.array([1,2,3])

In [23]:
print(a)

[1 2 3]


In [24]:
a=np.array([1,2,3],dtype = str)

In [6]:
print(a)

['1' '2' '3']


In [25]:
a=np.array([1,2,3],dtype = float)

In [9]:
print(a)

[1. 2. 3.]


In [11]:
#length of an array
len(a)

3

In [26]:
b=np.array([[1,2,3],[4,5,6]])

In [13]:
print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
#get dimensions of a numpy arary
a.ndim

1

In [15]:
b.ndim

2

In [32]:
#get s shape of a numpy array 
# shape tels us how many rows and column in an array
a_int=np.array([[1,2,3],
     [4,5,6],
     [7,8,9]])
print(a_int)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
